steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-f', 'Dockerfile',
    '-t','gcr.io/$PROJECT_ID/kubtmp:v$SHORT_SHA',
    '-t','gcr.io/$PROJECT_ID/kubtmp:latest',
    '.'
  ]
images: [
  'gcr.io/$PROJECT_ID/kubtmp:v$SHORT_SHA',
  'gcr.io/$PROJECT_ID/kubtmp:latest'
]